# vim ft=yaml
# travis-ci.org definition for tclclockmod build
# https://travis-ci.org/sebres/tclclockmod/
dist: xenial
sudo: true

language: c

# test it with both compilers:
compiler:
  - clang
  - gcc

addons:
  apt:
    packages:
      #- tcl8.6
      #- tcl8.6-dev

before_install:
  # ATM trusty-cosmic/xenial have too old tcl version (8.6.0/8.6.5), thus install newest 8.6.9 from disco ...
  - sudo add-apt-repository -y "deb http://archive.ubuntu.com/ubuntu disco main universe"
  - sudo apt-get update
  - sudo apt-get install --no-install-recommends -y -t disco tcl8.6 tcl8.6-dev
  # prerequirements (tclconfig)
  - test -d tclconfig || git clone https://github.com/tcltk/tclconfig.git ./tclconfig

before_script:
  # show version:
  - echo puts [info patchlevel] | tclsh
  - export BUILD_DIR=$(pwd)

script:
  - echo "Build with $CC ..."
  #- autoconf
  #- autoreconf -iv
  - cd unix
  - ../configure --with-tcl=/usr/lib/tcl8.6
  - make
  # current time and time-zone:
  - echo $TZ; timedatectl status
  # load local library and execute local test cases:
  - tclsh $BUILD_DIR/tests/all.tcl
  # test install:
  - sudo make install
  - echo 'if {[catch {package require tclclockmod; clock format -now}]} {puts stderr "ERROR!"; exit 1} else {puts "OK."}' | tclsh
  # clean all
  - make clean

matrix:
  fast_finish: true
