# vim ft=yaml
# travis-ci.org definition for tclclockmod build
# https://travis-ci.org/sebres/tclclockmod/
dist: trusty
sudo: true

language: c

# test it with both compilers:
compiler:
  - clang
  - gcc

addons:
  apt:
    packages:
      #- tcl8.6
      #- tcl8.6-dev

before_script:
  # ATM trusty has too old tcl version (8.6.0), thus install newest 8.6.7 ...
  - sudo add-apt-repository -y "deb http://us.archive.ubuntu.com/ubuntu/ artful main universe"
  - sudo apt-get update
  - sudo apt-get install -t artful -y tcl8.6 tcl8.6-dev
  # show version:
  - echo puts [info patchlevel] | tclsh
  - export BUILD_DIR=$(pwd)
  # prerequirements (tclconfig)
  - git clone https://github.com/tcltk/tclconfig.git ./tclconfig

script:
  - echo "Build with $CC ..."
  #- autoconf
  #- autoreconf -iv
  - cd unix
  - ../configure --with-tcl=/usr/lib/tcl8.6
  - make
  # load local library and execute local test cases:
  - tclsh $BUILD_DIR/tests/all.tcl
  # clean all
  - make clean

matrix:
  fast_finish: true
